# Nom du Workflow
name: CI/CD Pipeline
on:
  # Nous pouvons déclencher manuellement l'exécution du workflow
  workflow_dispatch:
  # Cela déclenche automatiquement le workflow lorsque nous faisons un push au master
  push:
    branches:
      - master
jobs:
  # Job qui exécute les tests
  tests:
    name: Unit tests
    # Exécuter sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest
    steps:
      # On doit checkout notre repository pour que le workflow puisse y accéder
      - uses: actions/checkout@v1
      # Installer JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      # Installer Maven cache
      - name: Cache Maven packages
        # Cela met en cache les dépendances, ce qui accélère l'exécution du workflow
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Pour finir, lancez les tests
      - name: Run Tests
        run: mvn -B test
